# Generated by Django 4.1.3 on 2022-11-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_dops_mentor_alter_user_employeenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dops',
            name='car',
        ),
        migrations.RemoveField(
            model_name='user',
            name='station',
        ),
        migrations.AddField(
            model_name='dops',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.user'),
        ),
        migrations.DeleteModel(
            name='car',
        ),
    ]
