export const useFirebaseUser = () => useState('firebaseUser', () => {})
export const useAuthNeeded = () => useState('authNeeded', () => {})
export const useIsAdminUser = () => useState('isAdminUser', () => {})
export const useIsRole = () => useState('isRole', () => {})
export const useIsAuthStateUpdated = () => useState('isAuthStateUpdated', () => {})